### PR TITLE
Fixes #334: remove firstRun from query string on onboarding dismiss

### LINKED ISSUE #334: Onboarding is wrongly redisplayed at refresh if you install the addon after making changes in the "Preview Panel"
**[Affected versions]:**
- Firefox 60.0.1 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Steps to reproduce]:**
1. Open the browser and navigate to https://color.firefox.com.
2. Make one change in the "Preview Panel".
3. Click the "Install Firefox Color" button and follow the flow in order to successfully install the add-on.
4. Click "Next" button on the onboarding until it is dismissed.
5. Refresh the page. 

**[Expected result]:**
- The page is refreshed.

**[Actual result]:**
- The "Onboarding" is wrongly displayed again. 

**[Additional Notes]:** 
- This issue is also reproducible if you install "Firefox Color" from a shared theme. 
- This issue is not reproducible when reopening the "Firefox Color" tab, or navigating to another website and returning to it. 
- Attached a screen recording of the issue:

screen recording of the issue

### PR DESCRIPTION
**Pull request by renancleyson-dev**
The cause of the redisplay was the URL parameter ```firstRun``` which persists after a refresh. To solve it, when handling the dismiss of Onboarding, it will remove the ```firstRun``` parameter from the URL.

Fixes #334

### CODE REVIEW

File: src/web/lib/components/Onboarding/index.js [hunk 1]
```diff
@@ -28,6 +29,15 @@ export default class Onboarding extends React.Component {
...
   handleDismiss = e => {
     if (e.target.classList.contains("dismissable")) {
+      const params = queryString.parse(window.location.search);
+      const pathname = window.location.pathname;
+
+      delete params.firstRun;
+      let stringifiedParams = queryString.stringify(params);
+
+      stringifiedParams = `${stringifiedParams && "?"}${stringifiedParams}`;
+      history.replaceState({}, "", `${pathname}${stringifiedParams}`);
```
Comment (Rob--W) [inline src/web/lib/components/Onboarding/index.js:39]: Use `history.state` instead of `{}`. Otherwise you may overwrite existing stored history, which isn't desirable.

And use `window.history` instead of `history` (not really needed, but let's do it for consistency with `window.history` and `window.location` here/elsewhere in the codebase).

**Review by Rob--W — CHANGES_REQUESTED** [review]
Thanks for the patch! Just one minor comment.

**Review by Rob--W — APPROVED** [review]
