### PR TITLE
fix advance color bugs

### LINKED ISSUE #934: Color picker section spills out of designated space when too many custom colors are added
Preconditions:
1. Go to about:config and change the “xpinstall.signatures.required” pref to “false”
2. Access https://color.stage.mozaws.net/
3. Click on the “Advanced colors” tab
4. Click on “Firefox Color Extension” link from the right side panel
5. On the newly opened page, click on “Unsigned add-on for color.stage.mozaws.net “
6. Follow the instructions on the doorhangers and install the Firefox Color add-on

Steps to reproduce:
1. Access https://color.stage.mozaws.net/
2. Click on the “Advanced colors” tab
3. Set a different color for each property
NOTE: Notice how each time a new/custom color is set for a property, a color square is added at the bottom of the Color picker section
4. Observe that when new/custom colors are set for each property, the Color picker section enlarges vertically and spills out of the designated space

Expected results:
The Color picker section should retain its dimensions when new/custom colors are added for each property.

Actual results:
The Color picker section enlarges vertically and spills out when new/custom colors are added for each property.

Affected versions:
- Nightly 79.0b1/20200629224419
- Beta Developer Edition 80.0a1/20200629154604

Affected OSes:
- Windows 10 64-bit
- Ubuntu 16.04 LTS

Nightly screenshot:
Nightly spill

Beta Developer Edition screenshot:
Beta spill

### LINKED ISSUE #936: “Tab Loading” property is not functional
Preconditions:
1. Go to about:config and change the “xpinstall.signatures.required” pref to “false”
2. Access https://color.stage.mozaws.net/
3. Click on the “Advanced colors” tab
4. Click on “Firefox Color Extension” link from the right side panel
5. On the newly opened page, click on “Unsigned add-on for color.stage.mozaws.net “
6. Follow the instructions on the doorhangers and install the Firefox Color add-on

Steps to reproduce:
1. Access https://color.stage.mozaws.net/
2. Click on the “Advanced colors” tab
3. Scroll to the “Tab Loading” property and set a color for it, for example Yellow
NOTE: This property is responsible for the tab loading indicator (short back and forth animation) and tab loading color burst when loading/reloading tabs. 
4. Open a new tab and go to https://www.youtube.com/
5. Reload the page
6. Observe that the color set through the “Tab Loading” property was not applied
NOTE: 
The actual color of the tab loading indicator and tab loading burst are set through 2 properties from the “Custom colors” tab:
- the tab loading indicator color is set through the “Toolbar Icons and Text” property
- the tab loading burst color is set through the “Tab Highlight Color” property

Expected results:
The color set through the “Tab Loading” property should be properly applied to the elements it is responsible for i.e. the tab loading indicator and tab loading color burst as described in https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme#colors “tab_loading” section.

Actual results:
The color set through the “Tab Loading” property is not applied.

Affected versions:
- Nightly 80.0a1/20200701093012
- Beta Developer Edition 79.0b2/20200630191632
- Release Unbranded 77.0.1/20200602222727

Affected OSes:
- Windows 10 64-bit
- Ubuntu 16.04 LTS

2020-07-01_15h51_46

2020-07-01_15h52_04

tab loading

### PR DESCRIPTION
**Pull request by andreicristianpetcu**
Fixes #936.
Fixes #934.

### CODE REVIEW

File: src/lib/themes.js [hunk 1]
```diff
@@ -261,10 +261,12 @@ export const convertToBrowserTheme = (themeData, bgImages, customBackgrounds) =>
   Object.keys(theme.colors).forEach(key => {
     newTheme.colors[key] = colorToCSS(theme.colors[key]);
   });
-
-  // TODO: we will need to actually create this field in
-  // theme manifests as part of #93.
-  newTheme.colors.tab_loading = colorToCSS(theme.colors.tab_line);
+  console.log(theme.colors);
```
Comment (Rob--W) [inline src/lib/themes.js:264]: Remove `console.log`.

**Comment by Rob--W** [comment]
PS. If you edit the PR and add the magic keywords

```
Fixes #936.
Fixes #934.
```

... then the PR would automatically be linked to those issues (which helps with visibility), and those issues would automatically be closed when the PR is merged.

File: src/web/lib/components/StorageSpaceInformation/index.scss [hunk 2]
```diff
@@ -5,6 +5,7 @@
   flex-direction: column;
   align-items: center;
   line-height: 1.5;
+  padding-top: 10px;
```
Comment (Rob--W) [inline src/web/lib/components/StorageSpaceInformation/index.scss:8]: This is shared by all tabs. To make sure that the gap is only added where we want it, remove this and add `margin-bottom: 10px;` to `.theme-colors-editor__list`. Note that the element itself already had `padding: 16px` at each side, but that failed to deliver the desired results because the content was clipped (with scrollbars).

File: src/web/lib/components/ThemeBuilder/index.scss [hunk 3]
```diff
@@ -83,7 +83,7 @@
   .theme-builder__content {
     background: var(--white-100);
     margin: 0 auto;
-    height: 400px;
+    height: 445px;
```
Comment (Rob--W) [inline src/web/lib/components/ThemeBuilder/index.scss:86]: 425px works now.

File: src/web/lib/components/ThemeColorsEditor/index.scss [hunk 4]
```diff
@@ -20,7 +20,7 @@
   padding: $grid * 4;
   position: relative;
   flex: 1 1 640px;
-  height: 320px;
+  height: 400px;
```
Comment (Rob--W) [inline src/web/lib/components/ThemeColorsEditor/index.scss:23]: Make it 350px. Then there is enough space around the storage-space-information element to look appealing in both the Custom and Advanced Colors tab.

**Comment by andreicristianpetcu** [comment]
Done @Rob--W :champagne:

File: src/web/lib/components/ThemeColorsEditor/index.scss [hunk 5]
```diff
@@ -20,8 +20,9 @@
   padding: $grid * 4;
   position: relative;
   flex: 1 1 640px;
-  height: 320px;
+  height: 350px;
   overflow: auto;
+  padding-bottom: 10px;
```
Comment (Rob--W) [inline src/web/lib/components/ThemeColorsEditor/index.scss:25]: It hould be `margin-bottom`. `padding-bottom` is inside the box, which would still be hidden by the scrollbars.

margin-bottom is outside the box.

**Comment by andreicristianpetcu** [comment]
Done

**Comment by andreicristianpetcu** [comment]
Any update with the release @Rob--W ?

**Comment by Rob--W** [comment]
The add-on is in the review queue on AMO. Once approved, I'll publish the latest version of the site. This will all happen within a few days.

**Comment by andreicristianpetcu** [comment]
Thank you for investing all this time in a project that is basically in maintenance. I really appreciate it! :heart: @Rob--W

**Comment by Rob--W** [comment]
Version 2.1.6 of the add-on has been approved, and I just updated the website to match. I did a quick check and it seems to be working as intended.

**Comment by andreicristianpetcu** [comment]
Once I started to port my themes to FF color I started to see issues :)))
I did not add ARGB for the ones that I needed to.... 
popup_highlight
sidebar_highlight_text
sidebar_text
toolbar_field_separator
toolbar_field_text_focus
toolbar_top_separator
How my theme looks 
image
http://localhost:8080/?theme=XQAAAAKmBAAAAAAAAABBKYhm849SCicxcUhCHjNpdzzyWMw6jC7AjsFFvBq6bJb_pTIEztZDnJzUQhD-FvSzC0EJgjLntIeQ3eFXB2dFAz5qr7nage4lSjQN8HT2PztF1_2o_8cLNvsqO6kPj4elEC0VG4hnOYqIV3ZQZqvAHslb9NVQNZ9oCyZ7t_cEuONPMx_grMMZ6fZBR0EmzF2Czi1qMurGq8wWTy-SkNcJIslJjH3vhFgRBXbMT--VDouoTaCzVi1GisAPtE3xMpZS9eGwnmjzjFvYHa_dQzf2kKnYgYhoTZvpEWTYZkFtMIJOrgc58qEfusdpN28rXJVRyz3jLJQ-11hf9WCyhWDX-oYp7NKByOjg61gVWqrr8utj1OIVC4To7Ef4S8i7LlFZe1GwHDe9GgCM_pj5VOXACkimNFqDbrNiJK-3o-8NJP1aiVr4uXhgw2NN63DU6nc5Qt9GPJ5iut-hbhzfTHzZiwTnJ6_267IF3e2BEVsLNZSt5hU-1Cb_WdosFkjuM8BhK0xHIMMSi5FVbhxQsPhtKng_eiQgOm2VGH8W7x0t5l_9BrcO

How it should look. https://addons.mozilla.org/en-US/firefox/addon/borderless-dark/?src=search
image

**Comment by andreicristianpetcu** [comment]
I got a close aproximation to my theme without alpha. Maybe I'll send in another PR soon :smile: 
image
https://color.firefox.com/?theme=XQAAAAJuBAAAAAAAAABBKYhm849SCicxcUhA3DJozHnOMuprjJIF9jJb-FWu-LKNPPR7QEVwEchbrYDpU0TML3WJHDuqqbxDwW31jv3GZ5hvMvMhiQXynt-0bl-j-9cLJkvthNcb0jrhLDSYQOJFf0FV3Dw3wpXVGP5f5N-DX26ctWmKCGwwgzAjqRhHzvajRZ6XAw2FLmknF51JbIUfcgP3TNJ8zvVJCmjYH1Db-VxCiQG3XqWv74FyAih4TSDmHZUyS2utJX-ViDEr_NzIxldusOIyuUNh_nKpg-fnjzqr1g68Jj13hlsfNX4uc76NoRIuwNJnhJ4RSGtmNfjzVdL-Ck2SSKkJ_7RMWmfL-rfe6q3FC-JXig1DIRjdJ2HcthUeDZNeIZl6nYPwP4HtRTqo6YAzEWof0mDaqNNGwwZO3nxIVr6FAVWdUcnzuFCsfqwx6XdyZsDaOCAXIO9BLHwg5EHA7q9ZmujQBX8DV5LEeXQLBDWDlrgYuxThoINgvJYpkxzHJushF2yCM5JeNA5A8f1p1cDtdQosRoco2B-nkRzbjdNFnP_jD1BP
